config/routes.rb
Rails.application.routes.draw do
  post 'views/rate'

  get 'views/review'

  get 'views/show'

  get 'views/average'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/failure'

  get 'sessions/destroy'

  get 'welcome/index'

  get '/login', :to => 'sessions#new', :as => :login
  
  get '/auth/:provider/callback', :to => 'sessions#create'
  
  get '/logout', :to => 'sessions#destroy'
  
  get '/auth/failure', :to => 'sessions#failure'

  resources :movies
  resources :views
  root 'welcome#index'

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
	belongs_to :user
	validates :provider, :uid, :presence => true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	
end

app/models/movie_rate.rb
class MovieRate < ActiveRecord::Base
  belongs_to :view
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :authorizations
	validates :name, :email, :presence => true
end

app/models/view.rb
class View < ActiveRecord::Base
	has_many :movie_rates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_filter :check_rack_mini_profiler
def check_rack_mini_profiler
  # for example - if current_user.admin?
  if params[:rmp]
    Rack::MiniProfiler.authorize_request
  end
end
end

app/controllers/movies_controller.rb
require "net/http"
require "uri"
require 'rubygems'
require 'json'
class MoviesController < ApplicationController
    def new
    end

    def show

    end



    def index
        @view= View.joins(:movie_rates).pluck(:movId, :name, :overview, :year, :rate, :review, :photo).uniq
    end


    def create
    	@movie=Movie.new(movie_params)
    	#render inline: @movie.title
        
        if !(@movie.title?)
            #byebug
            @movie.title = " ";
        end
    	#url="http://api.themoviedb.org/3/search/movie?query="+@movie.title+"&api_key=060a9ae33fe170591b00683218658ee6&year="+@movie.year+"&sort_by=release_date.desc"
    	if(@movie.genre?)
            url="http://api.themoviedb.org/3/discover/movie?api_key=20930962c5239d3b881390ecb5b0248d&with_genres="+@movie.genre+"&year="+@movie.year+" "
        else
            url="http://api.themoviedb.org/3/search/movie?query="+@movie.title+"&api_key=060a9ae33fe170591b00683218658ee6&year="+@movie.year+"&sort_by=release_date.desc"
        end
        uri = URI.parse(url)
		http = Net::HTTP.new(uri.host, uri.port)
		request = Net::HTTP::Get.new(uri.request_uri)
		response = http.request(request)

		parsed = JSON.parse(response.body)
		str=""
        @movieDetails=parsed
        #redirect_to :action =>'new'
        render "new", :locals => {:movie =>Movie.first, :movieDetails => @movieDetails}
 		#parsed["results"].each do |i|
		#	str= str + "MOVIE NAME :- " + i["title"] + "   RELEASE YEAR :- " + i["release_date"]+"\n"

			
		#end
	    #render inline: str

    #render plain: params[:movie].inspect
    end
    private
    def movie_params
    	params.require(:movie).permit(:title, :year, :genre)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	auth_hash = request.env['omniauth.auth']
 
  	@authorization = Authorization.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
  	if @authorization
    	#render :text => "Welcome back #{@authorization.user.name}! You have already signed up."
      render template: session[:redirect], :locals => {:user => User.first, :userDetails => @authorization.user.name, :uId => @authorization.uid}
      session[:userDetails] = @authorization.user.name 
      session[:uId] = @authorization.uid
  	else
    	user = User.new :name => auth_hash["info"]["name"], :email => auth_hash["info"]["email"]
    	user.authorizations.build :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    	user.save
 
    	render :text => "Hi #{user.name}! You've signed up."
  	end
  end

  def destroy
   	session[:user_id] = nil
    session[:userDetails]=nil
    session[:uId] = nil
    #render template: "welcome/index"
    render template: session[:redirect]
  end

  def failure
  	render :text => "Sorry, but you didn't allow access to our app!"
  end
end

app/controllers/views_controller.rb
require 'date'
require 'json'
class ViewsController < ApplicationController
  def new
	@view = View.new
  end
  def index
      @movie = View.joins(:movie_rates)
  end
  
  
  def create
  
 	  @view = View.new
 	  @view.name = params[:view][:title]
 	  @view.movId = params[:view][:mid].to_i
 	  @view.year = Date.parse(params[:view][:date])
 	  @view.photo = params[:view][:img]
 	  @view.overview = params[:view][:overview]
    @total_rating = ""
    @total_rating = total
    @average_rating = ""
    @average_rating = average

    #@average = MovieRate.select("movId,avg(rate) as average_rate,sum(rate) as total_rate").group("movId").order('average_rate DESC')
    @average_rating=JSON.parse(@average_rating)
    if(@average_rating.empty? != true)
      @average_rating=@average_rating[0]["average_rating"]
    else
      @average_rating=""
    end
    @total_rating=JSON.parse(@total_rating)
    if(@total_rating.empty? != true)
      @total_rating=@total_rating[0]["total_rating"]
    else
      @total_rating=""
    end

    if(View.exists?(movId: @view.movId))
    else
	     @view.save
    end
    
    @reviews = viewreview
    @reviews=JSON.parse(@reviews)

    render "new", :locals => {:view =>@view, :average => @average_rating,:total => @total_rating, :reviews => @reviews}
    
  end
  def rate
  	@rate = MovieRate.new()
    @rate.uId = session[:uId]
    @rate.uName = session[:userDetails]
  	@rate.movId = params[:rate][:mid]
    @rate.rate = params[:rate][:rating]
    @rate.review = params[:rate][:review]
    @view_id = viewId
    @view_id = JSON.parse(@view_id)
    @rate.view_id = @view_id[0]["id"]
    @alreadyvoted=checkRate
    @a=false
    @alreadyvoted.each do |i|
      if(i["movId"] == @rate.movId)
        @a=true
      end
    end
    #render plain: @a.inspect
    if(!@a)
      @rate.save
      #render "show", :locals => {:rate => @rate}
    end
    
    @v = eval(params[:rate][:view])
    @view = View.new
    @view.photo = @v["photo"]
    @view.name = @v["name"]
    @view.movId=@v["movId"]
    @view.overview=@v["overview"]
    @view.year=@v["year"]

    
    @view1=View.find(@rate.view_id)
    @avg_rating = MovieRate.where(movId: @rate.movId).average(:rate)
    @view1[:avgrating]=@avg_rating
    @view1.save

    if(!@a)
      render "show", :locals => {:view => @view}
    end
    
    
  end

  def checkRate
    @mid = MovieRate.select("movId").where("uId = ?", session[:uId]).to_json
    @mid=JSON.parse(@mid)
    
  end

  def review
    @topmovie= topmovie
    @topmovie=JSON.parse(@topmovie)

    @botmovie= botmovie
    @botmovie=JSON.parse(@botmovie)
   # @movjoin =View.joins(:movie_rates).pluck(:name, :photo)
    @movjoin =View.select("name, avgrating, photo, year").order('avgrating DESC').limit(5).to_json
    @movjoin = JSON.parse(@movjoin)

  end

  def show
  end

  def average
    MovieRate.select("avg(rate) as average_rating").group("movId").having("movId = ?", @view.movId).to_json
  end

  def total
    MovieRate.select("count(rate) as total_rating").group("movId").having("movId = ?", @view.movId).to_json
  end

  def viewreview
    MovieRate.select("uName, review").where("movId = ?", @view.movId).to_json
  end

  def viewId
    View.select("views.id").where("movId = ?", @rate.movId).to_json
  end

  def topmovie
    MovieRate.select("movId, avg(rate) as average_rating").group('movId').order('average_rating DESC').limit(5).to_json
  
  end

  def botmovie
    
  MovieRate.select("movId, avg(rate) as average_rating").group('movId').order('average_rating ASC').limit(5).to_json
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
<head>
  <title>PopcornMovies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
  body{
  	
  	background: url("/assets/back.jpg") no-repeat center center fixed; 
  	-webkit-background-size: cover;
  	-moz-background-size: cover;
  	-o-background-size: cover;
  	background-size: cover;
  	background-opacity: .01;
  }
  </style>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<div style="position:absolute; margin-left:30cm">
	<%= link_to "Back", root_path %></div>
<div>
<h1 style="position:absolute; margin-left:300px">Listing movies already rated and reviewed</h1><br>
<div style="width:20cm; margin: auto; border: 5px solid black; position: absolute; margin-top:50px; margin-left:250px">

		<% @sno=1 %>
		<% @view.each do |i| %>
			<div>		
				
				<p style="float: left;"><%= image_tag("http://image.tmdb.org/t/p/w185/"+i[6]) %></p>
				<p><%= @sno %></p>
				
				<p><b>Movie title: </b><%= i[1] %></p>
				<p><b>Year: </b><%= i[3] %></p>
				<p><b>Overview: </b><%= i[2]%></p>
			</div>
			<br><br><br><br><br><br><br><br>
		
			<% @sno += 1 %>
		<%end%>
</div>

app/views/movies/monthyear.html.erb
<%= form_for :movie, url: movies_path do |f|%>
<div>
<%= f.label :month %>&nbsp<%= f.text_field :month%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= f.label :year %>&nbsp<%= f.text_field :year%>

<%= f.submit "Search"%>
</div>

<%end%>

app/views/movies/new.html.erb
<style>
table, th, td {
    border: 1px solid black;
}
table{
	position: absolute;
	margin-left: 50px;
	width: 80%;
	text-align: center;
}

th {
    height: 50px;
}
tr {
	height: 40px;
}
</style>

<div style="position:absolute; margin-left:29cm">
	<% if !(session[:userDetails]) %>
	
	<%= link_to "Signin With Facebook", "/auth/facebook" %>
	<%session[:redirect]="movies/new"%>

<% else %>
	<p> Welcome <%= session[:userDetails] %>!</p>
	<%= link_to "Logout", "/logout" %>
	<%session[:redirect]="movies/new"%>
<% end %>
<br><br><%= link_to "Home Page", root_path%><br>
</div>
<div>
<h1> Searcing movies according to filters</h1>
</div>
<%= form_for :movie, url: movies_path do |f|%>
<div>
<%= f.label :title %>&nbsp<%= f.text_field :title%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= f.label :year %>&nbsp<%= f.text_field :year%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= f.label :genre %>&nbsp<%= f.text_field :genre%>

<%= f.submit "Search movie"%>
</div>

<%end%>
<br><br



<%if @movieDetails!=nil %>
<!--<%= @movieDetails.inspect %>-->
	<div style="position: absolute; margin-left: 50px"><b>Results of the search</b></div>
	<br>
	<table>
		<th>S.No</th>
		<th>Movie title</th>
		<th>Year</th>
		<th>View Page</th>
		<% @sno=1 %>
		<% @movieDetails["results"].each do |i| %>
		
				<tr>
					<td><%= @sno %></td> 
					<td><%= i["title"] %></td>
					<td><%= i["release_date"] %></td>
					<td><%= link_to "View", {:controller => "views", :view => {"title" => i["title"] , "mid" => i["id"], "date" => i["release_date"], "img" => i["poster_path"], "overview" => i["overview"]}}, :method => :post %></td>

				</tr>
				<% @sno += 1 %>
		<%end%>

	</table>
	<%end%>

app/views/views/average.html.erb
<h1>Views#average</h1>
<p>Find me in app/views/views/average.html.erb</p>

app/views/views/index.html.erb
<h1>movies</h1>
<%= @movie.inspect %>

app/views/views/new.html.erb
<div style="position:absolute; margin-left:30cm">
	<% if !(session[:userDetails]) %>
	
	<%= link_to "Signin With Facebook", "/auth/facebook" %>
	<%session[:redirect]="movies/new"%>

<% else %>
	<p> Welcome <%= session[:userDetails] %>!</p>
	<%= link_to "Logout", "/logout" %>
	<%session[:redirect]="moviess/new"%>
<% end %>
<br><br><%= link_to "Search page", new_movie_path %>
<br><br><%= link_to "Home Page", root_path%><br>
</div>
<div style="width:1000px; margin: auto; border: 2px solid black; position: absolute; margin-top:10px; margin-left:100px">
	<div style="text-align:center"><%= image_tag("http://image.tmdb.org/t/p/w185/"+@view.photo)%></div>
	<h1 style="text-align:center"><%=@view.name%></h1>
	<h3 style="text-align:center"><%=@view.year%></h3>


	<p><b>Overview : </b><%=@view.overview%></p>
	<%if @average_rating!=""%>
	<p><b>Average rating : </b><%=@average_rating%></p>
	<p><b>Total votes: </b><%=@total_rating%></p>
	<%end%>
	<div>
		<%if reviews.empty?!=true%>
		<p><b>List of reviews : </b></p>
		<div style="position: relative; margin-left: 100px">
		<% @reviews.each do |i| %>
			<%if i["review"]!=""%>
			<p><%=i["uName"]%> : <%=i["review"]%></p>
		<%end%>
		<%end%>	
		</div>
		<%end%>
		
	</div>
	<br>
	<% if (session[:userDetails]) %>
		<div style="text-align:center">
			<%= form_for :rate, url: views_rate_path do |f|%>
				Rate the movie&nbsp
				<%= f.hidden_field :view, :value => {"name" => @view.name, "year" => @view.year.to_s, "overview" => @view.overview, "photo" => @view.photo, "movId" => @view.movId} %>
				<%= f.hidden_field :mid, :value => @view.movId %>
				<%= f.text_field :rating%><br><br>
				
				Review the movie &nbsp
				<%= f.text_field :review%><br><br>
				<%= f.submit "Submit"%>
			<%end%>
		</div>
	<%else%><div style="color:red; text-align: center;"><b>Login to rate the movie</b></div>
	<%end%>
	
	<br>
	<br>
</div>

app/views/views/rate.html.erb
<h1>You have already rated the movie!!</h1>
<%= link_to "Home Page", root_path%><br>
<%= link_to "Search Page", new_movie_path%>

app/views/views/review.html.erb
	

<div style="position:absolute; margin-left:30cm">
	<%= link_to "Back", root_path %></div>
<div>
<h1 style="position:absolute; margin-left:300px">Top rated movies</h1><br>
<div style="width:20cm; margin: auto; border: 5px solid black; position: absolute; margin-top:50px; margin-left:250px">

		<% @sno=1 %>
		<% @movjoin.each do |i| %>
			<div>		
				
				<p style="float: left;"><%= image_tag("http://image.tmdb.org/t/p/w185/"+i["photo"]) %></p>
				<p><%= @sno %></p>
				
				<p><b>Movie title: </b><%= i["name"] %></p>
				<p><b>Year: </b><%= i["year"] %></p>
				<p><b>Average rating: </b><%= i["avgrating"]%></p>
			</div>
			<br><br><br><br><br><br><br><br><br><br>
		
			<% @sno += 1 %>
		<%end%>
</div>

app/views/views/show.html.erb
<h1>Rate and review added successfully!!</h1>
<%= link_to "Home Page", root_path%><br>
<%= link_to "Search Page", new_movie_path%>

app/views/welcome/index.html.erb
<style>
body{
  
  	
  	background: url("/assets/welcome_page.jpg") no-repeat center center fixed; 
  	-webkit-background-size: cover;
  	-moz-background-size: cover;
  	-o-background-size: cover;
  	background-size: cover;
  	background-opacity: .01;
 
  }
 </style>
 <div style="position:absolute; margin-left:29cm; color: white; margin-top: 20px">
	<% if !(session[:userDetails]) %>
	
	<%= link_to "Signin With Facebook", "/auth/facebook", {style: "color: white"} %>
  <%session[:redirect]="welcome/index"%>

<% else %>
	<p> Welcome <%= session[:userDetails] %>!</p>
	<%= link_to "Logout", "/logout", {style: "color: white"} %>
  <%session[:redirect]="welcome/index"%>
<% end %>
</div>
<div style="position:absolute; margin-top: 150px; margin-left:100px; align:center; color:white">
<h1>Welcome to Popcorn Movies</h1>
<p><%= link_to "Search for Movies", new_movie_path, {style: "color: white"}%></p><br>
<p><%= link_to "List of movies rated", movies_path, {style: "color: white"} %></p><br>
<p><%= link_to "Top rated movies", views_review_path, {style: "color: white"} %></p>
</div>